<?php
/**
 * @see Mage_Payment_Block_Info
 */
?>
<?php echo $this->escapeHtml($this->getMethod()->getTitle()) ?>

<?php if ($_specificInfo = $this->getSpecificInformation()):?>
    <table>
        <?php foreach ($_specificInfo as $_label => $_value):?>
            <tr>
                <td><?php echo $this->escapeHtml($_label)?>:</td>
                <td><?php echo nl2br(implode($this->getValueAsArray($_value, true), "\n"))?></td>
            </tr>
        <?php endforeach; ?>
    </table>
    <p><?php echo $this->__('In Installment '); echo $this->getInstallments() ?>x</p>
    <p><?php echo $this->__('Sales receipt (NSU): '); echo $this->getNsu() ?></p>
<?php endif;?>

<?php echo $this->getChildHtml()?>
