version: '3.3'
services:
    selenium:
        image: selenium/hub
        container_name: selenium
        ports:
        - "4444"
    chrome:
        image: selenium/node-chrome-debug
        container_name: chrome
        depends_on:
        - selenium
        links:
        - selenium:hub
        environment:
        - HUB_HOST=selenium
        - HUB_PORT=4444
    magento1db:
        image: vindi/mysql-magento1-ci
        container_name: magento1_db
        ports:
        - "3306"
    magento1web:
        image: vindi/apache-magento1-ci
        container_name: vindi.local
        depends_on:
        - magento1db
        - chrome
        ports:
        - "443:443"
        links:
        - magento1db:mysql
        - chrome
        environment:
        - API_KEY=${API_KEY}
networks:
    default:
        external:
            name: webproxy