version: '3.3'
services:
    selenium:
        image: selenium/standalone-chrome
        container_name: selenium
        ports:
        - "4444"
        volumes:
        - /dev/shm:/dev/shm
    magento1db:
        image: vindi/mysql-magento1-ci
        container_name: magento1_db
        ports:
        - "3306"
    magento1web:
        image: vindi/apache-magento1-ci
        container_name: vindi.local
        env_file:
          - .env
        depends_on:
        - magento1db
        ports:
        - "443:443"
        links:
        - magento1db:mysql
networks:
    default:
        external:
            name: webproxy