version: '3.3'
services:
    magento1_db:
        image: vindi/mysql_magento1
        container_name: magento1_db
        ports:
        - "3306"
    magento1_web:
        image: vindi/apache_magento1
        container_name: magento1_web
        depends_on:
        - magento1_db
        ports:
        - "80:80"
        links:
        - magento1_db:mysql
networks:
    default:
        external:
            name: webproxy